### ISSUE TITLE
Fix Cinnamon 3.2.2 Support for Themes

### ISSUE THREAD

**Issue by daemonspudguy** [Elbullazul/Redmond-Themes#18]
I have an issue on the latest version of Cinnamon. I am using the XP Themes. All themes are strange looking.

**Comment by daemonspudguy** [comment]
![image](https://cloud.githubusercontent.com/assets/24438557/20990109/49e2c64a-bca5-11e6-9928-fa5bdd3393ea.png)

**Comment by Elbullazul** [comment]
add the following code at the end of the cinnamon.css file. I think it should fix it, at least until cinnamon 3.2 gets stable enough I can work on it without problem.

```css
.starkmenu-background {
    border: solid 1px transparent;
    border-image: url("menu-bg.png") 12 12 67 42;
    box-shadow: 2px 2px 2px rgba(0,0,0,0.5);
    padding: 55px 1px 29px 1px;
}
```
